# Generated by Django 3.1.3 on 2020-11-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0003_auto_20201105_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='test_field',
            field=models.TextField(blank=True),
        ),
    ]
