# Generated by Django 3.1.3 on 2020-11-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0004_author_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='test_field',
        ),
    ]
