# Generated by Django 3.1.3 on 2020-11-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0005_remove_author_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='test_field',
            field=models.TextField(blank=True),
        ),
    ]
